#!/bin/sh

# Made by DiDA for iOSGods.com! - Version 1.2.1 - Visit https://ghostbin.com/paste/7nf78 for an up-to-date version!


#################################################################################

iosgods_binary="/Library/PreferenceBundles/PROJECTNAME.bundle/Binary/BINARYNAME"
iosgods_target_directory="/var/mobile/Containers/Bundle/Application/*/APPNAME.app/"
iosgods_lipoarm64="/usr/bin/LipoARM64NAME"
lipoarm64_binarytarget="BINARYNAMETOPATCH"

#################################################################################


set -e

ig_mv_perms() {
    # Check if the specified binary exists in the location provided above, otherwise output an error
    if [ ! -f "${iosgods_binary}" ]; then
        printf "${iosgods_binary} file couldn't be found, please check if the specified location is correct. If the issue still persists, ask for help on iOSGods.com\\n"
        exit 1
    fi

    # Check if there is a '*' character in the target directory variable and process if that's the case
    if [ "${iosgods_target_directory}" != "${iosgods_target_directory%%\***}" ]; then
        base_iosgods_target_directory="${iosgods_target_directory%%\***}"
        prefix_iosgods_target_directory="${iosgods_target_directory##**\*}"

        # Search prefix_iosgods_target_directory on base_iosgods_target_directory directory
        for t in $base_iosgods_target_directory/* ; do
            if [ -d "${t}${prefix_iosgods_target_directory}" ]; then
                # Found, replace iosgods_target_directory with real path
                iosgods_target_directory="${t}${prefix_iosgods_target_directory}"
                break
            else
                continue
            fi
        done
    fi

    if [ ! -d "${iosgods_target_directory}" ]; then
        printf "${iosgods_target_directory} directory wasn't found, please make sure you have the app installed or ask for support on iOSGods.com"
        exit 1
    fi

    # Changing permissions prior to moving to simplify code
    chmod 755 "${iosgods_binary}"
    chown mobile:mobile "${iosgods_binary}"
	
	# Moving thinned binary to the app's directory
    printf "** Applying the hack...\\n"
    mv "${iosgods_binary}" "${iosgods_target_directory}"
}


case "${1}" in
    configure)

        # Read sw_vers output and act upon it
        case "$(sw_vers -productVersion)" in
            5*|6*|7*|8*) # If iOS 5, 6, 7, or 8 is detected, it will run LipoARM64 to patch the binary
                printf "*************************************\\n"
                printf "* iOS 8 or below has been detected. *\\n"
                printf "*************************************\\n\\n"

				"${iosgods_lipoarm64}" "${lipoarm64_binarytarget}"
				
                ;;

            9*|10*) # If iOS 9+ is detected, apply the thinned binary
                printf "****************************\\n"
                printf "* iOS 9+ has been detected. *\\n"
                printf "****************************\\n\\n"

                ig_mv_perms
				
                ;;
        esac
        ;;
    abort-upgrade|abort-deconfigure|abort-remove)
        ;;
    *)
        printf "%s\\n" "${0} called with unknown argument \`${1}'" 1>&2
        exit 1
        ;;
esac
